# Generated by Django 3.1.2 on 2020-10-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='submission_dae',
            new_name='submission_date',
        ),
    ]
